import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;

public class DVDUtilityTest {
    public static void main(String[] args) {
        DVD[] dvdArray = {
                new DVD("Zoolander (Warner Brothers/ Blu-ray)","Warner Brothers",2001,"Comedy",14.97),
                new DVD("Zombie Wars: Battle Of The Bone","Eagle One Media",2008,"Horror",16.95),
                new DVD("Zombie Games: The Knackery (Special Edition)","Eagle One Media",2009,"Horror",16.95),
                new DVD("Zombie Apocalypse (2012)","Discovery Channel",2012,"Documentary",14.93),
                new DVD("ZOFO Duet: ZOFOrbit: A Space Odyssey (Audio Only Blu-ray/CD Combo)","Dorian Sono Luminus",2014,"Music",24.99),
                new DVD("Yuyushiki: The Complete Collection","Sentai FilmWorks",2013,"Anime",49.98),
                new DVD("Yu-Gi-Oh!: Classic: Season 5, Vol. 3","New Video",2005,"Anime",19.95),
                new DVD("Yu-Gi-Oh!: Classic: Season 5, Vol. 2","New Video",2005,"Anime",24.95),
                new DVD("Yu-Gi-Oh!: Bonds Beyond Time (Blu-ray)","Flatiron Film Company",2010,"Anime",19.97),
                new DVD("Yu-Gi-Oh!: Bonds Beyond Time","Flatiron Film Company",2010,"Anime",14.93),
                new DVD("Young Doctor's Notebook","BBC Home Video",2012,"TV Classics",19.96),
                new DVD("You, Me And Dupree (Widescreen/ Blu-ray w/ Digital Copy)","Universal",2006,"Comedy",19.98),
                new DVD("Yamibo: Darkness, The Hat, And The Travelers Of The Books","Anime Works",2003,"Anime",29.98),
                new DVD("Xpress Train (Critical Mass)","Critical Mass",2000,"Anime",14.99),
                new DVD("Xinyi Wudao: Key Teachings Of Dai Family Internal Martial Arts","Singing Dragon",2014,"Special Interest",49.95),
                new DVD("Xena: Warrior Princess (Universal): Season 5","Universal",1999,"TV Classics",22.98),
                new DVD("WWE: Payback 2014","WWE Home Video",2014,"Special Interest",14.93),
                new DVD("WWE: Money In The Bank 2014","WWE Home Video",2014,"Special Interest",14.93),
                new DVD("WWE: Men Of Mayhem","WWE Home Video",2014,"Special Interest",14.93),
                new DVD("WWE: Extreme Rules 2014","WWE Home Video",2014,"Special Interest",14.93),
                new DVD("WWE: Batista Animal Unleashed (Blu-ray)","WWE Home Video",2014,"Special Interest",39.95),
                new DVD("WWE: Batista Animal Unleashed","WWE Home Video",2014,"Special Interest",29.93),
                new DVD("WWE Multi-Feature: Triple H Double Feature: Inside Out (2011) / The Chaperone","Image",2011,"VAR",12.98),
                new DVD("Wrinkles","Cinedigm Entertainment",2011,"Animation",29.95),
                new DVD("Wreck Of The Hesperus (Choice Collection/ On Demand DVD-R)","Sony Pictures",1948,"Drama",20.95),
                new DVD("Wrath Of The Crows","MTI",2013,"Suspense/Thriller",24.95),
                new DVD("World War Z (Blu-ray)","Paramount",2013,"Action/Adventure",14.99),
                new DVD("World War Z (Blu-ray 3D/ DVD & Blu-ray Combo)","Paramount",2013,"Action/Adventure",19.99),
                new DVD("World Outdoor Trials Review: 2013","Duke Video",2014,"Sports",24.95),
                new DVD("World Motocross Review: 2013","Duke Video",2014,"Sports",24.95),
                new DVD("Workaholics: Season 4 (Blu-ray)","Comedy Central",2013,"TV Classics",22.99),
                new DVD("Workaholics: Season 4","Comedy Central",2013,"TV Classics",19.99),
                new DVD("Workaholics: Season 3 (Blu-ray)","Paramount",2012,"TV Classics",12.99),
                new DVD("WordGirl: Monkey Business","PBS",2013,"Animation",9.99),
                new DVD("Word Of The Lord: Seeing Jesus In The Prophets","Crossway Books",2014,"Special Interest",89.99),
                new DVD("Woodstock: 3 Days Of Peace & Music (Director's Cut/ 40th Anniversary Limited Edition Revisited/ Blu-ray)","Warner Brothers",1970,"Music",39.96),
                new DVD("Woman In White (Acorn Media)","Acorn Media",1997,"Mystery/Suspense",19.99),
                new DVD("Wolf Of Wall Street (DVD & Blu-ray Combo)","Paramount",2013,"Comedy",14.99),
                new DVD("Wolf Creek 2 (DVD & Blu-ray Combo)","Image",2013,"Horror",34.97),
                new DVD("Wolf Creek 2","Image",2013,"Horror",27.97),
                new DVD("Wolf (Mill Creek Entertainment)","Mill Creek Entertainment",1994,"Horror",9.98),
                new DVD("Without A Trace (2002): The Complete 7th Season (Archive Collection/ On Demand DVD-R)","Warner Brothers Digital Dist.",2008,"TV Classics",47.99),
                new DVD("Witches Of East End: The Complete 1st Season","Fox",2013,"TV Classics",29.98),
                new DVD("Witch Who Came From The Sea (Cinema Epoch/ Special Edition)","Cinema Epoch",1976,"Horror",19.95),
                new DVD("Wishes","Maddox",2014,"Family",14.99),
                new DVD("Wiser Together: Learning To Live The Right Way","Zondervan",2014,"Special Interest",26.99),
                new DVD("Wiser Together Study Guide + DVD: Learning To Live The Right Way (Book w/ DVD)","Zondervan",2014,"Special Interest",36.99),
                new DVD("Winx Club (New Video): The Original Season 2, Vol. 2: Charmix Power","New Video",2005,"Anime",14.95),
                new DVD("Winx Club (New Video): The Original Season 2, Vol. 1: Shadow Phoenix","New Video",2005,"Anime",14.95),
                new DVD("Winx Club (New Video): The Original Season 2","New Video",2005,"Anime",24.95),
                new DVD("Winter's Tale (2014/ Rental Ready)","Warner Brothers",2014,"Fantasy",22.97),
                new DVD("Winter's Tale (2014/ DVD & Blu-ray Combo w/ Digital Copy)","Warner Brothers",2014,"Fantasy",35.99),
                new DVD("Winter's Tale (2014/ Blu-ray/ Rental Ready)","Warner Brothers",2014,"Fantasy",24.97),
                new DVD("Winter's Tale (2014)","Warner Brothers",2014,"Fantasy",28.98),
                new DVD("Wind Will Carry Us (Blu-ray)","Cohen Media Group",1999,"Foreign",39.98),
                new DVD("Wind Will Carry Us","Cohen Media Group",1999,"Foreign",29.98),
                new DVD("Will You Still Love Me Tomorrow?","Film Movement",2013,"Foreign",24.95),
                new DVD("Wild Brazil: Land Of Fire And Flood","BBC Home Video",2014,"Documentary",24.98),
                new DVD("Whoopi Goldberg Presents: Moms Mabley","HBO",2013,"TV Classics",19.98),
                new DVD("Who's Harry Crumb? (Mill Creek Entertainment)","Mill Creek Entertainment",1989,"Comedy",9.98),
                new DVD("When The Iron Bird Flies: Tibetan Buddhism Arrives In The West","Kino International",2012,"Documentary",29.95),
                new DVD("When I Walk","Passion River",2013,"Documentary",29.95),
                new DVD("What's In A Name?","First Run Features",2012,"Foreign",24.95),
                new DVD("What Would You Do For Love?","E1 Entertainment",2013,"Comedy",14.98),
                new DVD("What Richard Did","New Video",2012,"Drama",26.95),
                new DVD("What If?: [The Helene Mayer Story]","ITN Distribution",2008,"Documentary",99.95),
                new DVD("Wet Behind The Ears","Cinema Libre",2013,"Comedy",19.95),
                new DVD("Weekend Of A Champion","MPI Home Video",2013,"Documentary",24.98),
                new DVD("Wedding Workflow For Photographers: The Complete Guide To Processing And Delivering Your Wedding Photos In 2 Days ... (DVD-ROM)","Peachpit Press",2014,"Special Interest",99.99),
                new DVD("Wedding Video (2012)","Level 33 Entertainment",2012,"Comedy",19.99),
                new DVD("Web Wargame Toolkit (Book w/ DVD)","Mercury Learning & Information",2015,"Special Interest",39.95),
                new DVD("We Always Lie To Strangers","Virgil Films and Entertainment",2013,"Documentary",19.99),
                new DVD("Way Of The Wicked (Blu-ray)","Image",2014,"Suspense/Thriller",29.97),
                new DVD("Way Of The Wicked","Image",2014,"Suspense/Thriller",27.97),
                new DVD("Watermark (2013/ Blu-ray)","E1 Entertainment",2013,"Documentary",29.98),
                new DVD("Watermark (2013)","E1 Entertainment",2013,"Documentary",24.98),
                new DVD("Watercolor Unleashed: Painting White Flowers","North Light Books",2014,"Special Interest",31.99),
                new DVD("WataMote: No Matter How I Look At It, It's You Guys Fault I'm Not Popular: The Complete Collection (Blu-ray)","Sentai FilmWorks",2013,"Anime",69.98),
                new DVD("WataMote: No Matter How I Look At It, It's You Guys Fault I'm Not Popular: The Complete Collection","Sentai FilmWorks",2013,"Anime",59.98),
                new DVD("Warehouse 13: Season 5","Universal",2013,"TV Classics",39.98),
                new DVD("Walls Came Tumbling Down (Choice Collection/ On Demand DVD-R)","Sony Pictures",1946,"Action/Adventure",20.95),
                new DVD("Walking Dead: The Complete 4th Season (Blu-ray/ Limited Edition)","Anchor Bay",2013,"TV Classics",129.99),
                new DVD("Walking Dead: The Complete 4th Season (Blu-ray)","Anchor Bay",2013,"TV Classics",79.99),
                new DVD("Walking Dead: The Complete 4th Season","Anchor Bay",2013,"TV Classics",69.98),
                new DVD("Walk Of Shame (Blu-ray w/ Digital Copy)","Universal",2014,"Comedy",26.98),
                new DVD("Walk Of Shame","Universal",2014,"Comedy",19.98),
                new DVD("Waking The Dead (TV Series): The Complete : Season 9","BBC Home Video",2010,"TV Classics",39.98),
                new DVD("Wahlburgers: The Complete 1st Season","Lions Gate",2014,"TV Classics",19.98),
                new DVD("Voodoo Dollz","Retromedia",2008,"Late Night",14.99),
                new DVD("Viva Max","Cheezy Flicks",1969,"Comedy",14.95),
                new DVD("Understanding Revelation In 60 Minutes","Harvest House Publishers",2012,"Special Interest",19.99),
                new DVD("Under The Skin (2013/ Blu-ray)","Lions Gate",2013,"SciFi",24.99),
                new DVD("Viva Las Vegas (Warner Brothers/ 50th Anniversary Edition/ Blu-ray)","Warner Brothers",1964,"Musical",27.98),
                new DVD("Visitors (2013/ DVD & Blu-ray Combo)","Cinedigm",2013,"Documentary",34.95),
                new DVD("Visitors (2013)","Cinedigm",2013,"Documentary",29.95),
                new DVD("Vinyl (2012/ Blu-ray)","Shout! Factory",2012,"Comedy",19.97),
                new DVD("Vinyl (2012)","Shout! Factory",2012,"Comedy",14.98),
                new DVD("Video Resources On DVD For Stats: Modeling The World (DVD-ROM)","Pearson",2014,"Special Interest",33.33),
        };

        DVD[] anotherArray = {
                new DVD("Zoolander (Warner Brothers/ Blu-ray)","Warner Brothers",2001,"Comedy",14.97),
                new DVD("Zombie Wars: Battle Of The Bone","Eagle One Media",2008,"Horror",16.95),
                new DVD("Zombie Games: The Knackery (Special Edition)","Eagle One Media",2009,"Horror",16.95),
                new DVD("Zombie Apocalypse (2012)","Discovery Channel",2012,"Documentary",14.93),
                new DVD("ZOFO Duet: ZOFOrbit: A Space Odyssey (Audio Only Blu-ray/CD Combo)","Dorian Sono Luminus",2014,"Music",24.99),
                new DVD("Yuyushiki: The Complete Collection","Sentai FilmWorks",2013,"Anime",49.98),
                new DVD("Yu-Gi-Oh!: Classic: Season 5, Vol. 3","New Video",2005,"Anime",19.95),
                new DVD("Yu-Gi-Oh!: Classic: Season 5, Vol. 2","New Video",2005,"Anime",24.95),
                new DVD("Yu-Gi-Oh!: Bonds Beyond Time (Blu-ray)","Flatiron Film Company",2010,"Anime",19.97),
                new DVD("Yu-Gi-Oh!: Bonds Beyond Time","Flatiron Film Company",2010,"Anime",14.93),
                new DVD("Young Doctor's Notebook","BBC Home Video",2012,"TV Classics",19.96),
                new DVD("You, Me And Dupree (Widescreen/ Blu-ray w/ Digital Copy)","Universal",2006,"Comedy",19.98),
                new DVD("Yamibo: Darkness, The Hat, And The Travelers Of The Books","Anime Works",2003,"Anime",29.98),
                new DVD("Xpress Train (Critical Mass)","Critical Mass",2000,"Anime",14.99),
                new DVD("Xinyi Wudao: Key Teachings Of Dai Family Internal Martial Arts","Singing Dragon",2014,"Special Interest",49.95),
                new DVD("Xena: Warrior Princess (Universal): Season 5","Universal",1999,"TV Classics",22.98),
                new DVD("WWE: Payback 2014","WWE Home Video",2014,"Special Interest",14.93),
                new DVD("WWE: Money In The Bank 2014","WWE Home Video",2014,"Special Interest",14.93),
                new DVD("WWE: Men Of Mayhem","WWE Home Video",2014,"Special Interest",14.93),
                new DVD("WWE: Extreme Rules 2014","WWE Home Video",2014,"Special Interest",14.93),
                new DVD("WWE: Batista Animal Unleashed (Blu-ray)","WWE Home Video",2014,"Special Interest",39.95),
                new DVD("WWE: Batista Animal Unleashed","WWE Home Video",2014,"Special Interest",29.93),
                new DVD("WWE Multi-Feature: Triple H Double Feature: Inside Out (2011) / The Chaperone","Image",2011,"VAR",12.98),
                new DVD("Wrinkles","Cinedigm Entertainment",2011,"Animation",29.95),
                new DVD("Wreck Of The Hesperus (Choice Collection/ On Demand DVD-R)","Sony Pictures",1948,"Drama",20.95),
                new DVD("Wrath Of The Crows","MTI",2013,"Suspense/Thriller",24.95),
                new DVD("World War Z (Blu-ray)","Paramount",2013,"Action/Adventure",14.99),
                new DVD("World War Z (Blu-ray 3D/ DVD & Blu-ray Combo)","Paramount",2013,"Action/Adventure",19.99),
                new DVD("World Outdoor Trials Review: 2013","Duke Video",2014,"Sports",24.95),
                new DVD("World Motocross Review: 2013","Duke Video",2014,"Sports",24.95),
                new DVD("Workaholics: Season 4 (Blu-ray)","Comedy Central",2013,"TV Classics",22.99),
                new DVD("Workaholics: Season 4","Comedy Central",2013,"TV Classics",19.99),
                new DVD("Workaholics: Season 3 (Blu-ray)","Paramount",2012,"TV Classics",12.99),
                new DVD("WordGirl: Monkey Business","PBS",2013,"Animation",9.99),
                new DVD("Word Of The Lord: Seeing Jesus In The Prophets","Crossway Books",2014,"Special Interest",89.99),
                new DVD("Woodstock: 3 Days Of Peace & Music (Director's Cut/ 40th Anniversary Limited Edition Revisited/ Blu-ray)","Warner Brothers",1970,"Music",39.96),
                new DVD("Woman In White (Acorn Media)","Acorn Media",1997,"Mystery/Suspense",19.99),
                new DVD("Wolf Of Wall Street (DVD & Blu-ray Combo)","Paramount",2013,"Comedy",14.99),
                new DVD("Wolf Creek 2 (DVD & Blu-ray Combo)","Image",2013,"Horror",34.97),
                new DVD("Wolf Creek 2","Image",2013,"Horror",27.97),
                new DVD("Wolf (Mill Creek Entertainment)","Mill Creek Entertainment",1994,"Horror",9.98),
                new DVD("Without A Trace (2002): The Complete 7th Season (Archive Collection/ On Demand DVD-R)","Warner Brothers Digital Dist.",2008,"TV Classics",47.99),
                new DVD("Witches Of East End: The Complete 1st Season","Fox",2013,"TV Classics",29.98),
                new DVD("Witch Who Came From The Sea (Cinema Epoch/ Special Edition)","Cinema Epoch",1976,"Horror",19.95),
                new DVD("Wishes","Maddox",2014,"Family",14.99),
                new DVD("Wiser Together: Learning To Live The Right Way","Zondervan",2014,"Special Interest",26.99),
                new DVD("Wiser Together Study Guide + DVD: Learning To Live The Right Way (Book w/ DVD)","Zondervan",2014,"Special Interest",36.99),
                new DVD("Winx Club (New Video): The Original Season 2, Vol. 2: Charmix Power","New Video",2005,"Anime",14.95),
                new DVD("Winx Club (New Video): The Original Season 2, Vol. 1: Shadow Phoenix","New Video",2005,"Anime",14.95),
                new DVD("Winx Club (New Video): The Original Season 2","New Video",2005,"Anime",24.95),
                new DVD("Winter's Tale (2014/ Rental Ready)","Warner Brothers",2014,"Fantasy",22.97),
                new DVD("Winter's Tale (2014/ DVD & Blu-ray Combo w/ Digital Copy)","Warner Brothers",2014,"Fantasy",35.99),
                new DVD("Winter's Tale (2014/ Blu-ray/ Rental Ready)","Warner Brothers",2014,"Fantasy",24.97),
                new DVD("Winter's Tale (2014)","Warner Brothers",2014,"Fantasy",28.98),
                new DVD("Wind Will Carry Us (Blu-ray)","Cohen Media Group",1999,"Foreign",39.98),
                new DVD("Wind Will Carry Us","Cohen Media Group",1999,"Foreign",29.98),
                new DVD("Will You Still Love Me Tomorrow?","Film Movement",2013,"Foreign",24.95),
                new DVD("Wild Brazil: Land Of Fire And Flood","BBC Home Video",2014,"Documentary",24.98),
                new DVD("Whoopi Goldberg Presents: Moms Mabley","HBO",2013,"TV Classics",19.98),
                new DVD("Who's Harry Crumb? (Mill Creek Entertainment)","Mill Creek Entertainment",1989,"Comedy",9.98),
                new DVD("When The Iron Bird Flies: Tibetan Buddhism Arrives In The West","Kino International",2012,"Documentary",29.95),
                new DVD("When I Walk","Passion River",2013,"Documentary",29.95),
                new DVD("What's In A Name?","First Run Features",2012,"Foreign",24.95),
                new DVD("What Would You Do For Love?","E1 Entertainment",2013,"Comedy",14.98),
                new DVD("What Richard Did","New Video",2012,"Drama",26.95),
                new DVD("What If?: [The Helene Mayer Story]","ITN Distribution",2008,"Documentary",99.95),
                new DVD("Wet Behind The Ears","Cinema Libre",2013,"Comedy",19.95),
                new DVD("Weekend Of A Champion","MPI Home Video",2013,"Documentary",24.98),
                new DVD("Wedding Workflow For Photographers: The Complete Guide To Processing And Delivering Your Wedding Photos In 2 Days ... (DVD-ROM)","Peachpit Press",2014,"Special Interest",99.99),
                new DVD("Wedding Video (2012)","Level 33 Entertainment",2012,"Comedy",19.99),
                new DVD("Web Wargame Toolkit (Book w/ DVD)","Mercury Learning & Information",2015,"Special Interest",39.95),
                new DVD("We Always Lie To Strangers","Virgil Films and Entertainment",2013,"Documentary",19.99),
                new DVD("Way Of The Wicked (Blu-ray)","Image",2014,"Suspense/Thriller",29.97),
                new DVD("Way Of The Wicked","Image",2014,"Suspense/Thriller",27.97),
                new DVD("Watermark (2013/ Blu-ray)","E1 Entertainment",2013,"Documentary",29.98),
                new DVD("Watermark (2013)","E1 Entertainment",2013,"Documentary",24.98),
                new DVD("Watercolor Unleashed: Painting White Flowers","North Light Books",2014,"Special Interest",31.99),
                new DVD("WataMote: No Matter How I Look At It, It's You Guys Fault I'm Not Popular: The Complete Collection (Blu-ray)","Sentai FilmWorks",2013,"Anime",69.98),
                new DVD("WataMote: No Matter How I Look At It, It's You Guys Fault I'm Not Popular: The Complete Collection","Sentai FilmWorks",2013,"Anime",59.98),
                new DVD("Warehouse 13: Season 5","Universal",2013,"TV Classics",39.98),
                new DVD("Walls Came Tumbling Down (Choice Collection/ On Demand DVD-R)","Sony Pictures",1946,"Action/Adventure",20.95),
                new DVD("Walking Dead: The Complete 4th Season (Blu-ray/ Limited Edition)","Anchor Bay",2013,"TV Classics",129.99),
                new DVD("Walking Dead: The Complete 4th Season (Blu-ray)","Anchor Bay",2013,"TV Classics",79.99),
                new DVD("Walking Dead: The Complete 4th Season","Anchor Bay",2013,"TV Classics",69.98),
                new DVD("Walk Of Shame (Blu-ray w/ Digital Copy)","Universal",2014,"Comedy",26.98),
                new DVD("Walk Of Shame","Universal",2014,"Comedy",19.98),
                new DVD("Waking The Dead (TV Series): The Complete : Season 9","BBC Home Video",2010,"TV Classics",39.98),
                new DVD("Wahlburgers: The Complete 1st Season","Lions Gate",2014,"TV Classics",19.98),
                new DVD("Voodoo Dollz","Retromedia",2008,"Late Night",14.99),
                new DVD("Viva Max","Cheezy Flicks",1969,"Comedy",14.95),
                new DVD("Viva Las Vegas (Warner Brothers/ 50th Anniversary Edition/ Blu-ray)","Warner Brothers",1964,"Musical",27.98),
                new DVD("Visitors (2013/ DVD & Blu-ray Combo)","Cinedigm",2013,"Documentary",34.95),
                new DVD("Visitors (2013)","Cinedigm",2013,"Documentary",29.95),
                new DVD("Vinyl (2012/ Blu-ray)","Shout! Factory",2012,"Comedy",19.97),
                new DVD("Vinyl (2012)","Shout! Factory",2012,"Comedy",14.98),
                new DVD("Video Resources On DVD For Stats: Modeling The World (DVD-ROM)","Pearson",2014,"Special Interest",33.33),
                new DVD("Understanding Wood","Popular Woodworking Books",2014,"Special Interest",29.99),
                new DVD("Untold History Of The United States, Part 3: Reagan, Bush, Clinton, Bush, Obama (Blu-ray)","Warner Brothers",2012,"Documentary",19.98),
        };

        System.out.println("1. GetMostExpensiveDVD: ");
        System.out.println("test with null parameter: " + DVDUtility.getMostExpensiveDVD(null));
        System.out.println("test empty array parameter: " + DVDUtility.getMostExpensiveDVD(new DVD[0]));
        System.out.println("test with data: " + DVDUtility.getMostExpensiveDVD(dvdArray));

        System.out.println();
        System.out.println("2. getDVDWithGenre");
        System.out.println("null dvd:" + DVDUtility.getDVDWithGenre(null, "Comedy"));
        System.out.println("null genre:" + DVDUtility.getDVDWithGenre(dvdArray, null));
        System.out.println("Comedy dvds: " + DVDUtility.getDVDWithGenre(dvdArray, "Comedy").size());
        System.out.println("Action/Adventure dvds: " + DVDUtility.getDVDWithGenre(dvdArray, "Action/Adventure").size());
        System.out.println("Musical dvds: " + DVDUtility.getDVDWithGenre(dvdArray, "Musical").size());

        System.out.println();
        System.out.println("3. getDVDWithPriceBetween");
        System.out.println("number of DVDs (10 <= price < 20): " + DVDUtility.getDVDWithPriceBetween(dvdArray, 10, 20).size());

        
        System.out.println();
        System.out.println("4. getDVDTitlesInYear");
        System.out.println(Arrays.toString(DVDUtility.getDVDTitlesInYear(null, 2015)));
        String[] result = DVDUtility.getDVDTitlesInYear(dvdArray, 2015);
        System.out.println(Arrays.toString(result));

        System.out.println();
        System.out.println("5. getUniqueDVDs");
        System.out.println("null parameter: " + DVDUtility.getUniqueDVDs(null, anotherArray).size());
        System.out.println("two arrays: " + DVDUtility.getUniqueDVDs(dvdArray, anotherArray));


    }
}
